vich_uploader:
    db_driver: orm

    mappings:
       games:
           uri_prefix: /images/games
           upload_destination: '%kernel.project_dir%/public/images/games'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
