controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

GamingIndex:
    path: /
    controller: App\Controller\GameController::index

easyadmin:
    resource: .
    type: easyadmin.routes

dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index   
